/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tes;

import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.Connection;
import java.sql.DriverManager;  // Harus pakai ini, bukan "Drivermanager"
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;// Untuk Message Dialog


/**
 *
 * @author User
 */

public class BuatAkun extends javax.swing.JFrame {
    private java.sql.Statement St;
    private Connection con;
    private ResultSet rs; // Typo diperbaiki
    private String sql = ""; // Typo diperbaiki
    /**
     * Creates new form GUI
     */
    public BuatAkun() {
        initComponents();
        koneksiDB();
    }

    private void koneksiDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysavings", "root", ""); // Database connection
          
        } catch (Exception e) {
            System.out.println("Koneksi gagal: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jSlider1 = new javax.swing.JSlider();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tampil = new javax.swing.JTextArea();
        cbkelas = new javax.swing.JComboBox<>();
        cbNkelas = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbRkelas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jFormattedTextField1.setText("jFormattedTextField1");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 188, -1));

        jLabel1.setText("NAMA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 20));

        jLabel4.setText("KELAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 52, 20));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("✅ Oke, Simpan!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("❌ Nanti Dulu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 112, -1));

        Tampil.setColumns(20);
        Tampil.setRows(5);
        jScrollPane1.setViewportView(Tampil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 374, 590, 147));

        cbkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "RPL", "TP", "TBSM", "TKRO", "AKL" }));
        cbkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkelasActionPerformed(evt);
            }
        });
        getContentPane().add(cbkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        cbNkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", " 2", " 3", " 4", " 5" }));
        getContentPane().add(cbNkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 82, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel5.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel5.setText("<html>Buat<br><span style='line-height:50%;'>Akun</span></html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(439, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        cbRkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VI ", "VII ", "VIII ", "IX ", "X ", "XI ", "XII " }));
        cbRkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRkelasActionPerformed(evt);
            }
        });
        getContentPane().add(cbRkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 87, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Yuk, mulai nabung! Isi nama dan kelas dulu, ya!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jButton4.setText("Transaksi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nama = jTextField1.getText();
String Rkelas = cbRkelas.getSelectedItem().toString();
String kelas = cbkelas.getSelectedItem().toString();
String Nkelas = cbNkelas.getSelectedItem().toString();
int newId = -1; // ID otomatis yang akan dihasilkan
 PreparedStatement stmt = null; // Deklarasikan stmt di luar blok try-catch
String Sql = "INSERT INTO tbl_nasabah (Nama_nasabah, TTL, Kelas, Total_saldo) " +
             "VALUES (?, NOW(), ?, 0)"; // Deklarasikan Sql di luar try-catch
String checkSql = "SELECT COUNT(*) FROM tbl_nasabah WHERE Nama_nasabah = ? AND Kelas = ?"; // Query untuk memeriksa apakah sudah ada

if (nama.trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Form harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return; // Menghentikan eksekusi jika nama kosong
}

try {
    // Langkah 1: Memeriksa apakah data sudah ada di DB
    PreparedStatement checkStmt = con.prepareStatement(checkSql);
    checkStmt.setString(1, nama);
    checkStmt.setString(2, Rkelas + " " + kelas + " " + Nkelas); // Menggabungkan Rkelas, kelas, Nkelas
    ResultSet rsCheck = checkStmt.executeQuery();
    
    if (rsCheck.next()) {
        int count = rsCheck.getInt(1);
        if (count > 0) {
            JOptionPane.showMessageDialog(this, "Nama dan Kelas sudah terdaftar di database!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Jika data sudah ada, hentikan eksekusi
        }
    }

    // Langkah 2: Menyisipkan data baru jika belum ada
    stmt = con.prepareStatement(Sql, Statement.RETURN_GENERATED_KEYS);
    stmt.setString(1, nama);
    stmt.setString(2, Rkelas + " " + kelas + " " + Nkelas); // Menggabungkan Rkelas, kelas, Nkelas
    
    // Menjalankan query untuk memasukkan data baru
    stmt.executeUpdate();
    
    // Mendapatkan ID yang baru saja dihasilkan
    ResultSet generatedKeys = stmt.getGeneratedKeys();
    if (generatedKeys.next()) {
        newId = generatedKeys.getInt(1); // ID unik yang baru dibuat
        JOptionPane.showMessageDialog(this, "Buat Akun berhasil!");
    }
    
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    e.printStackTrace(); // Log error untuk debugging
} finally {
    try {
        if (stmt != null) stmt.close(); // Menutup PreparedStatement setelah selesai
    } catch (SQLException e) {
        e.printStackTrace(); // Log error jika terjadi kesalahan saat menutup PreparedStatement
    }
}

// Menampilkan hasil ID nasabah baru
Tampil.setText("Nama_Nasabah: " + nama + "\n" + "Kelas: " + Rkelas + kelas + Nkelas + "\n" + "ID_Nasabah: " + newId);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Halaman_awal signUP = new Halaman_awal(); // Membuat objek baru dari form SignUp
    signUP.setVisible(true); // Menampilkan jendela SignUp
    this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkelasActionPerformed

    private void cbRkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRkelasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Transaksi signUP = new Transaksi(); // Membuat objek baru dari form SignUp
    signUP.setVisible(true); // Menampilkan jendela SignUp
    this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuatAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Tampil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cbNkelas;
    private javax.swing.JComboBox<String> cbRkelas;
    private javax.swing.JComboBox<String> cbkelas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
